//! PR comment rendering for cockpitctl.
//!
//! Renderer must:
//! - be deterministic
//! - be budgeted
//! - link to artifacts rather than dumping content
//!
//! It should not parse sensor-specific markdown. Link only.

use cockpitctl_types::{CockpitConfig, CockpitReport, VerdictStatus, Severity};

fn status_badge(s: &VerdictStatus) -> &'static str {
    match s {
        VerdictStatus::Pass => "✅ pass",
        VerdictStatus::Warn => "⚠️ warn",
        VerdictStatus::Fail => "❌ fail",
        VerdictStatus::Skip => "⏭ skip",
    }
}

fn severity_badge(s: &Severity) -> &'static str {
    match s {
        Severity::Error => "❌",
        Severity::Warn => "⚠️",
        Severity::Info => "ℹ️",
    }
}

pub fn render_comment(report: &CockpitReport, cfg: &CockpitConfig) -> String {
    let mut out = String::new();

    out.push_str("<!-- cockpit:begin -->\n");
    out.push_str("## Cockpit\n\n");
    out.push_str("This comment is generated by `cockpitctl`. Details live in `artifacts/`.\n\n");

    out.push_str("### Summary\n\n");
    out.push_str("| Sensor | Status | Blocking | Notes |\n");
    out.push_str("|---|---:|---:|---|\n");

    for s in &report.sensors {
        let blocking = if s.blocking { "yes" } else { "no" };
        let mut notes = format!("`{}`", s.report_path);
        if let Some(c) = &s.comment_path {
            notes.push_str(&format!(" · `{}`", c));
        }
        if s.truncated {
            notes.push_str(" · _truncated_");
        }
        out.push_str(&format!("| `{}` | {} | {} | {} |\n", s.id, status_badge(&s.verdict.status), blocking, notes));
    }

    out.push_str("\n");

    // Highlights
    out.push_str("### Highlights\n\n");
    if report.highlights.is_empty() {
        out.push_str("_No highlights._\n\n");
    } else {
        let max = cfg.policy.max_highlights;
        out.push_str(&format!("(showing up to **{}**)\n\n", max));

        for (i, h) in report.highlights.iter().enumerate() {
            let f = &h.finding;
            let loc = match &f.location {
                Some(l) => {
                    let mut s = String::new();
                    if let Some(p) = &l.path { s.push_str(p); }
                    if let Some(line) = l.line { s.push_str(&format!(":{}", line)); }
                    if s.is_empty() { None } else { Some(s) }
                }
                None => None,
            };

            let loc_str = loc.map(|x| format!(" at `{}`", x)).unwrap_or_default();
            out.push_str(&format!(
                "{}. {} **{}**: `{}`{} — {}\n",
                i + 1,
                severity_badge(&f.severity),
                h.sensor_id,
                f.code,
                loc_str,
                f.message.replace('\n', " ")
            ));
        }
        out.push_str("\n");
    }

    // Sections: group sensors by section label, render in cfg.policy.section_order order.
    let mut by_section: std::collections::BTreeMap<String, Vec<&cockpitctl_types::SensorSummary>> =
        std::collections::BTreeMap::new();

    for s in &report.sensors {
        let section = cfg
            .sensors
            .get(&s.id)
            .and_then(|p| p.section.clone())
            .unwrap_or_else(|| "Other".to_string());
        by_section.entry(section).or_default().push(s);
    }

    for section in &cfg.policy.section_order {
        let Some(sensors) = by_section.get(section) else { continue; };
        out.push_str(&format!("### {}\n\n", section));
        for s in sensors {
            // Minimal, link-first line.
            let mut line = format!("- `{}`: {}", s.id, status_badge(&s.verdict.status));
            line.push_str(&format!(" · report `{}`", s.report_path));
            if let Some(c) = &s.comment_path {
                line.push_str(&format!(" · comment `{}`", c));
            }
            if let Some(p) = cfg.sensors.get(&s.id) {
                if let Some(repro) = &p.repro {
                    line.push_str(&format!("\n  - repro: `{}`", repro));
                }
            }
            out.push_str(&format!("{}\n", line));
        }
        out.push_str("\n");
    }

    out.push_str("<!-- cockpit:end -->\n");
    out
}
